name: t_widgets
description: "A collection of reusable Flutter custom widgets designed to simplify UI development, speed up prototyping, and enhance cross-platform apps."
version: 1.1.3
homepage: https://github.com/ThanCoder/t_widget.git
repository: https://github.com/ThanCoder/t_widget.git

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  than_pkg: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
