name: t_widgets
description: "A collection of reusable Flutter custom widgets designed to simplify UI development, speed up prototyping, and enhance cross-platform apps."
version: 2.2.2
homepage: https://github.com/ThanCoder/t_widget.git
repository: https://github.com/ThanCoder/t_widget.git

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.7
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.1.0
